// Dados extraídos das Atas de Conselho de Classe - 1º Bimestre 2026
// EE Carlos Bernardes Staut - Ribeirão dos Índios, SP

export interface Aluno {
  nome: string
  notas: Record<string, number | "TR">
  media: number
  classificacao: string
  atencao: boolean
}

export interface Turma {
  id: string
  nome: string
  nivel: "Ensino Fundamental" | "Ensino Médio"
  bimestre: string
  totalAlunos: number
  materias: string[]
  alunos: Aluno[]
}

export interface EscolaData {
  nome: string
  endereco: string
  cidade: string
  bimestre: string
  dataConselho: string
  turmas: Turma[]
}

// Função para classificar notas pedagogicamente
export function classificarNota(nota: number): string {
  if (nota <= 4) return "Abaixo do Básico"
  if (nota <= 6) return "Básico"
  if (nota <= 8) return "Adequado"
  return "Avançado"
}

// Função para obter cor da classificação
export function getCorClassificacao(classificacao: string): string {
  switch (classificacao) {
    case "Abaixo do Básico":
      return "bg-red-100 text-red-700 border-red-200"
    case "Básico":
      return "bg-amber-100 text-amber-700 border-amber-200"
    case "Adequado":
      return "bg-blue-100 text-blue-700 border-blue-200"
    case "Avançado":
      return "bg-emerald-100 text-emerald-700 border-emerald-200"
    default:
      return "bg-gray-100 text-gray-700 border-gray-200"
  }
}

// Função para calcular média
function calcularMedia(notas: Record<string, number | "TR">): number {
  const valores = Object.values(notas).filter((n): n is number => typeof n === "number")
  if (valores.length === 0) return 0
  return Number((valores.reduce((a, b) => a + b, 0) / valores.length).toFixed(1))
}

// Dados da 1ª Série - Ensino Médio
const materias1Serie = [
  "Arte",
  "Biologia",
  "Educação Financeira",
  "Educação Física",
  "Filosofia",
  "Física",
  "Geografia",
  "História",
  "Inglês",
  "Língua Portuguesa",
  "Matemática",
  "Química",
  "Redação e Leitura",
]

const alunos1Serie: Aluno[] = [
  {
    nome: "Alex de Souza Fonseca Junior",
    notas: {
      Arte: 8,
      Biologia: 8,
      "Educação Financeira": 8,
      "Educação Física": 10,
      Filosofia: 9,
      Física: 7,
      Geografia: 8,
      História: 8,
      Inglês: 8,
      "Língua Portuguesa": 8,
      Matemática: 7,
      Química: 8,
      "Redação e Leitura": 8,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
  {
    nome: "Carlos Eduardo de Jesus",
    notas: {
      Arte: 7,
      Biologia: 6,
      "Educação Financeira": 7,
      "Educação Física": 7,
      Filosofia: 6,
      Física: 4,
      Geografia: 6,
      História: 5,
      Inglês: 5,
      "Língua Portuguesa": 6,
      Matemática: 5,
      Química: 7,
      "Redação e Leitura": 6,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Enzo Ramos Mariano",
    notas: {
      Arte: 7,
      Biologia: 8,
      "Educação Financeira": 7,
      "Educação Física": 9,
      Filosofia: 7,
      Física: 7,
      Geografia: 6,
      História: 6,
      Inglês: 6,
      "Língua Portuguesa": 8,
      Matemática: 6,
      Química: 7,
      "Redação e Leitura": 6,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
  {
    nome: "Evelyn Marques da Silva",
    notas: {
      Arte: 7,
      Biologia: 7,
      "Educação Financeira": 8,
      "Educação Física": 7,
      Filosofia: 8,
      Física: 6,
      Geografia: 7,
      História: 9,
      Inglês: 6,
      "Língua Portuguesa": 7,
      Matemática: 6,
      Química: 8,
      "Redação e Leitura": 7,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
  {
    nome: "Guilherme de Aquino Vivian",
    notas: {
      Arte: 9,
      Biologia: 9,
      "Educação Financeira": 9,
      "Educação Física": 8,
      Filosofia: 9,
      Física: 8,
      Geografia: 9,
      História: 9,
      Inglês: 9,
      "Língua Portuguesa": 9,
      Matemática: 8,
      Química: 9,
      "Redação e Leitura": 9,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
  {
    nome: "Isabelle Rodrigues Ribeiro",
    notas: {
      Arte: 7,
      Biologia: 6,
      "Educação Financeira": 8,
      "Educação Física": 8,
      Filosofia: 6,
      Física: 6,
      Geografia: 7,
      História: 6,
      Inglês: 6,
      "Língua Portuguesa": 6,
      Matemática: 5,
      Química: 7,
      "Redação e Leitura": 7,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
  {
    nome: "João Lucas Vicente Ribeiro",
    notas: {
      Arte: 6,
      Biologia: 5,
      "Educação Financeira": 4,
      "Educação Física": 7,
      Filosofia: 5,
      Física: 4,
      Geografia: 6,
      História: 5,
      Inglês: 6,
      "Língua Portuguesa": 4,
      Matemática: 4,
      Química: 5,
      "Redação e Leitura": 6,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Larissa Dantas da Silva",
    notas: {
      Arte: 7,
      Biologia: 5,
      "Educação Financeira": 7,
      "Educação Física": 7,
      Filosofia: 7,
      Física: 5,
      Geografia: 7,
      História: 6,
      Inglês: 5,
      "Língua Portuguesa": 7,
      Matemática: 6,
      Química: 7,
      "Redação e Leitura": 8,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
  {
    nome: "Luma Gabrielly de Souza Santos",
    notas: {
      Arte: 7,
      Biologia: 7,
      "Educação Financeira": 6,
      "Educação Física": 7,
      Filosofia: 6,
      Física: 5,
      Geografia: 5,
      História: 8,
      Inglês: 5,
      "Língua Portuguesa": 7,
      Matemática: 6,
      Química: 8,
      "Redação e Leitura": 8,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
  {
    nome: "Maria Alice Soares Volpe Brito",
    notas: {
      Arte: 10,
      Biologia: 10,
      "Educação Financeira": 9,
      "Educação Física": 9,
      Filosofia: 10,
      Física: 9,
      Geografia: 10,
      História: 10,
      Inglês: 10,
      "Língua Portuguesa": 10,
      Matemática: 8,
      Química: 9,
      "Redação e Leitura": 9,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
  {
    nome: "Marina Purissimo e Silva",
    notas: {
      Arte: 8,
      Biologia: 5,
      "Educação Financeira": 6,
      "Educação Física": 7,
      Filosofia: 8,
      Física: 4,
      Geografia: 8,
      História: 8,
      Inglês: 7,
      "Língua Portuguesa": 7,
      Matemática: 5,
      Química: 6,
      "Redação e Leitura": 7,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Melissa Cristina dos Santos Dantas",
    notas: {
      Arte: 7,
      Biologia: 5,
      "Educação Financeira": 6,
      "Educação Física": 7,
      Filosofia: 6,
      Física: 5,
      Geografia: 4,
      História: 6,
      Inglês: 4,
      "Língua Portuguesa": 5,
      Matemática: 6,
      Química: 7,
      "Redação e Leitura": 6,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Miguel Estevam Boy",
    notas: {
      Arte: 5,
      Biologia: 5,
      "Educação Financeira": 5,
      "Educação Física": 7,
      Filosofia: 4,
      Física: 4,
      Geografia: 4,
      História: 5,
      Inglês: 4,
      "Língua Portuguesa": 4,
      Matemática: 4,
      Química: 6,
      "Redação e Leitura": 4,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Rita Vitoria dos Santos",
    notas: {
      Arte: 5,
      Biologia: 3,
      "Educação Financeira": 5,
      "Educação Física": 5,
      Filosofia: 4,
      Física: 3,
      Geografia: 3,
      História: 3,
      Inglês: 2,
      "Língua Portuguesa": 4,
      Matemática: 4,
      Química: 3,
      "Redação e Leitura": 5,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Tiago Gabriel de Sena",
    notas: {
      Arte: 6,
      Biologia: 7,
      "Educação Financeira": 7,
      "Educação Física": 7,
      Filosofia: 6,
      Física: 4,
      Geografia: 6,
      História: 5,
      Inglês: 5,
      "Língua Portuguesa": 5,
      Matemática: 5,
      Química: 5,
      "Redação e Leitura": 5,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Yasmim Bianca Alves de Oliveira",
    notas: {
      Arte: 7,
      Biologia: 5,
      "Educação Financeira": 7,
      "Educação Física": 8,
      Filosofia: 6,
      Física: 6,
      Geografia: 5,
      História: 6,
      Inglês: 5,
      "Língua Portuguesa": 7,
      Matemática: 7,
      Química: 3,
      "Redação e Leitura": 6,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
]

// Dados da 2ª Série - Ensino Médio
const materias2Serie = [
  "Arte e Mídias Digitais",
  "Biologia",
  "Educação Financeira",
  "Educação Física",
  "Liderança e Oratória",
  "Física",
  "Geografia",
  "História",
  "Língua Inglesa",
  "Língua Portuguesa",
  "Matemática",
  "Química",
  "Redação e Leitura",
  "Sociologia",
]

const alunos2Serie: Aluno[] = [
  {
    nome: "Ana Luiza Santos Baisar",
    notas: {
      "Arte e Mídias Digitais": 7,
      Biologia: 8,
      "Educação Financeira": 6,
      "Educação Física": 10,
      "Liderança e Oratória": 8,
      Física: 6,
      Geografia: 6,
      História: 6,
      "Língua Inglesa": 7,
      "Língua Portuguesa": 6,
      Matemática: 6,
      Química: 7,
      "Redação e Leitura": 8,
      Sociologia: 8,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
  {
    nome: "Bryan Henrique de Araujo",
    notas: {
      "Arte e Mídias Digitais": 8,
      Biologia: 9,
      "Educação Financeira": 6,
      "Educação Física": 10,
      "Liderança e Oratória": 7,
      Física: 6,
      Geografia: 7,
      História: 5,
      "Língua Inglesa": 8,
      "Língua Portuguesa": 7,
      Matemática: 4,
      Química: 7,
      "Redação e Leitura": 7,
      Sociologia: 7,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Daniel Gonçalves de Lima",
    notas: {
      "Arte e Mídias Digitais": 7,
      Biologia: 8,
      "Educação Financeira": 7,
      "Educação Física": 8,
      "Liderança e Oratória": 6,
      Física: 5,
      Geografia: 6,
      História: 7,
      "Língua Inglesa": 6,
      "Língua Portuguesa": 7,
      Matemática: 4,
      Química: 7,
      "Redação e Leitura": 7,
      Sociologia: 6,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "João Pedro Gois Rego",
    notas: {
      "Arte e Mídias Digitais": 7,
      Biologia: 6,
      "Educação Financeira": 5,
      "Educação Física": 9,
      "Liderança e Oratória": 6,
      Física: 5,
      Geografia: 6,
      História: 5,
      "Língua Inglesa": 3,
      "Língua Portuguesa": 6,
      Matemática: 4,
      Química: 6,
      "Redação e Leitura": 6,
      Sociologia: 6,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Maria Alice Alves Silva",
    notas: {
      "Arte e Mídias Digitais": 8,
      Biologia: 10,
      "Educação Financeira": 7,
      "Educação Física": 7,
      "Liderança e Oratória": 8,
      Física: 7,
      Geografia: 9,
      História: 8,
      "Língua Inglesa": 8,
      "Língua Portuguesa": 7,
      Matemática: 4,
      Química: 8,
      "Redação e Leitura": 8,
      Sociologia: 8,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Maria Heloisa Brito Silva",
    notas: {
      "Arte e Mídias Digitais": 5,
      Biologia: 6,
      "Educação Financeira": 5,
      "Educação Física": 7,
      "Liderança e Oratória": 6,
      Física: 5,
      Geografia: 5,
      História: 5,
      "Língua Inglesa": 5,
      "Língua Portuguesa": 5,
      Matemática: 5,
      Química: 4,
      "Redação e Leitura": 6,
      Sociologia: 5,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
  {
    nome: "Murillo Estevam Boy",
    notas: {
      "Arte e Mídias Digitais": 6,
      Biologia: 7,
      "Educação Financeira": 7,
      "Educação Física": 10,
      "Liderança e Oratória": 6,
      Física: 6,
      Geografia: 6,
      História: 6,
      "Língua Inglesa": 7,
      "Língua Portuguesa": 7,
      Matemática: 5,
      Química: 6,
      "Redação e Leitura": 7,
      Sociologia: 7,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
  {
    nome: "Sophia Gois Furini",
    notas: {
      "Arte e Mídias Digitais": 6,
      Biologia: 8,
      "Educação Financeira": 6,
      "Educação Física": 9,
      "Liderança e Oratória": 7,
      Física: 6,
      Geografia: 6,
      História: 6,
      "Língua Inglesa": 6,
      "Língua Portuguesa": 7,
      Matemática: 4,
      Química: 6,
      "Redação e Leitura": 7,
      Sociologia: 6,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Thalita Santos Gois",
    notas: {
      "Arte e Mídias Digitais": 6,
      Biologia: 7,
      "Educação Financeira": 5,
      "Educação Física": 8,
      "Liderança e Oratória": 7,
      Física: 4,
      Geografia: 6,
      História: 5,
      "Língua Inglesa": 6,
      "Língua Portuguesa": 4,
      Matemática: 4,
      Química: 4,
      "Redação e Leitura": 6,
      Sociologia: 5,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Wilherme Dantas da Silva",
    notas: {
      "Arte e Mídias Digitais": 8,
      Biologia: 10,
      "Educação Financeira": 7,
      "Educação Física": 9,
      "Liderança e Oratória": 8,
      Física: 5,
      Geografia: 5,
      História: 5,
      "Língua Inglesa": 5,
      "Língua Portuguesa": 6,
      Matemática: 4,
      Química: 7,
      "Redação e Leitura": 7,
      Sociologia: 7,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
]

// Dados da 3ª Série - Ensino Médio
const materias3Serie = [
  "Atualidades",
  "Projeto de Vida",
  "OE - Língua Portuguesa",
  "Educação Física",
  "OE - Matemática",
  "Física",
  "Aprofundamento de Geografia",
  "História",
  "Língua Inglesa",
  "Língua Portuguesa",
  "Matemática",
  "Aprofundamento de Filosofia",
  "Redação e Leitura",
  "Aprofundamento de Sociologia",
]

const alunos3Serie: Aluno[] = [
  {
    nome: "Alexandre Santos Araujo",
    notas: {
      Atualidades: 5,
      "Projeto de Vida": 7,
      "OE - Língua Portuguesa": 6,
      "Educação Física": 7,
      "OE - Matemática": 7,
      Física: 5,
      "Aprofundamento de Geografia": 7,
      História: 6,
      "Língua Inglesa": 5,
      "Língua Portuguesa": 7,
      Matemática: 5,
      "Aprofundamento de Filosofia": 8,
      "Redação e Leitura": 5,
      "Aprofundamento de Sociologia": 7,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
  {
    nome: "Ana Luiza Araujo Rocha",
    notas: {
      Atualidades: 6,
      "Projeto de Vida": 7,
      "OE - Língua Portuguesa": 6,
      "Educação Física": 10,
      "OE - Matemática": 5,
      Física: 4,
      "Aprofundamento de Geografia": 7,
      História: 6,
      "Língua Inglesa": 6,
      "Língua Portuguesa": 5,
      Matemática: 4,
      "Aprofundamento de Filosofia": 6,
      "Redação e Leitura": 4,
      "Aprofundamento de Sociologia": 5,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Bianca Cristina dos Santos Dantas",
    notas: {
      Atualidades: 8,
      "Projeto de Vida": 5,
      "OE - Língua Portuguesa": 5,
      "Educação Física": 7,
      "OE - Matemática": 5,
      Física: 5,
      "Aprofundamento de Geografia": 8,
      História: 5,
      "Língua Inglesa": 6,
      "Língua Portuguesa": 5,
      Matemática: 5,
      "Aprofundamento de Filosofia": 8,
      "Redação e Leitura": 6,
      "Aprofundamento de Sociologia": 8,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
  {
    nome: "Caue Almeida Souza",
    notas: {
      Atualidades: 7,
      "Projeto de Vida": 6,
      "OE - Língua Portuguesa": 4,
      "Educação Física": 9,
      "OE - Matemática": 7,
      Física: 5,
      "Aprofundamento de Geografia": 8,
      História: 6,
      "Língua Inglesa": 5,
      "Língua Portuguesa": 5,
      Matemática: 4,
      "Aprofundamento de Filosofia": 8,
      "Redação e Leitura": 4,
      "Aprofundamento de Sociologia": 8,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Dominique Cristiny Manzarin",
    notas: {
      Atualidades: 7,
      "Projeto de Vida": 6,
      "OE - Língua Portuguesa": 7,
      "Educação Física": 8,
      "OE - Matemática": 6,
      Física: 7,
      "Aprofundamento de Geografia": 7,
      História: 7,
      "Língua Inglesa": 7,
      "Língua Portuguesa": 6,
      Matemática: 5,
      "Aprofundamento de Filosofia": 8,
      "Redação e Leitura": 7,
      "Aprofundamento de Sociologia": 7,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
  {
    nome: "Gabriel Junior Sena",
    notas: {
      Atualidades: 8,
      "Projeto de Vida": 8,
      "OE - Língua Portuguesa": 8,
      "Educação Física": 8,
      "OE - Matemática": 6,
      Física: 5,
      "Aprofundamento de Geografia": 8,
      História: 8,
      "Língua Inglesa": 6,
      "Língua Portuguesa": 7,
      Matemática: 7,
      "Aprofundamento de Filosofia": 7,
      "Redação e Leitura": 7,
      "Aprofundamento de Sociologia": 8,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
  {
    nome: "Glenda Samanta de Oliveira Bordon",
    notas: {
      Atualidades: 6,
      "Projeto de Vida": 5,
      "OE - Língua Portuguesa": 5,
      "Educação Física": 7,
      "OE - Matemática": 4,
      Física: 5,
      "Aprofundamento de Geografia": 5,
      História: 4,
      "Língua Inglesa": 4,
      "Língua Portuguesa": 5,
      Matemática: 4,
      "Aprofundamento de Filosofia": 6,
      "Redação e Leitura": 5,
      "Aprofundamento de Sociologia": 5,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Guilherme Bressa Reis",
    notas: {
      Atualidades: 7,
      "Projeto de Vida": 8,
      "OE - Língua Portuguesa": 7,
      "Educação Física": 10,
      "OE - Matemática": 6,
      Física: 6,
      "Aprofundamento de Geografia": 7,
      História: 7,
      "Língua Inglesa": 5,
      "Língua Portuguesa": 6,
      Matemática: 5,
      "Aprofundamento de Filosofia": 8,
      "Redação e Leitura": 6,
      "Aprofundamento de Sociologia": 8,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
  {
    nome: "Gustavo Brito Silva",
    notas: {
      Atualidades: 8,
      "Projeto de Vida": 8,
      "OE - Língua Portuguesa": 7,
      "Educação Física": 10,
      "OE - Matemática": 5,
      Física: 7,
      "Aprofundamento de Geografia": 7,
      História: 7,
      "Língua Inglesa": 5,
      "Língua Portuguesa": 7,
      Matemática: 6,
      "Aprofundamento de Filosofia": 7,
      "Redação e Leitura": 6,
      "Aprofundamento de Sociologia": 8,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
  {
    nome: "Hugo Cancian",
    notas: {
      Atualidades: 7,
      "Projeto de Vida": 8,
      "OE - Língua Portuguesa": 8,
      "Educação Física": 8,
      "OE - Matemática": 6,
      Física: 6,
      "Aprofundamento de Geografia": 8,
      História: 8,
      "Língua Inglesa": 7,
      "Língua Portuguesa": 7,
      Matemática: 5,
      "Aprofundamento de Filosofia": 8,
      "Redação e Leitura": 6,
      "Aprofundamento de Sociologia": 8,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
  {
    nome: "Isadora Aquino Rodrigues Alves",
    notas: {
      Atualidades: 8,
      "Projeto de Vida": 6,
      "OE - Língua Portuguesa": 6,
      "Educação Física": 8,
      "OE - Matemática": 6,
      Física: 6,
      "Aprofundamento de Geografia": 9,
      História: 8,
      "Língua Inglesa": 6,
      "Língua Portuguesa": 6,
      Matemática: 5,
      "Aprofundamento de Filosofia": 8,
      "Redação e Leitura": 6,
      "Aprofundamento de Sociologia": 9,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
  {
    nome: "João Lucas Santos Silva",
    notas: {
      Atualidades: 8,
      "Projeto de Vida": 8,
      "OE - Língua Portuguesa": 7,
      "Educação Física": 9,
      "OE - Matemática": 5,
      Física: 8,
      "Aprofundamento de Geografia": 8,
      História: 7,
      "Língua Inglesa": 6,
      "Língua Portuguesa": 8,
      Matemática: 6,
      "Aprofundamento de Filosofia": 7,
      "Redação e Leitura": 7,
      "Aprofundamento de Sociologia": 6,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
  {
    nome: "João Victor Augusto Vieira",
    notas: {
      Atualidades: 8,
      "Projeto de Vida": 10,
      "OE - Língua Portuguesa": 7,
      "Educação Física": 9,
      "OE - Matemática": 5,
      Física: 8,
      "Aprofundamento de Geografia": 9,
      História: 8,
      "Língua Inglesa": 8,
      "Língua Portuguesa": 7,
      Matemática: 8,
      "Aprofundamento de Filosofia": 8,
      "Redação e Leitura": 6,
      "Aprofundamento de Sociologia": 8,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
  {
    nome: "Kauã Rego da Rocha",
    notas: {
      Atualidades: 7,
      "Projeto de Vida": 6,
      "OE - Língua Portuguesa": 4,
      "Educação Física": 9,
      "OE - Matemática": 4,
      Física: 4,
      "Aprofundamento de Geografia": 7,
      História: 4,
      "Língua Inglesa": 4,
      "Língua Portuguesa": 4,
      Matemática: 3,
      "Aprofundamento de Filosofia": 7,
      "Redação e Leitura": 4,
      "Aprofundamento de Sociologia": 6,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Kayke Rafael Defacio da Silva",
    notas: {
      Atualidades: 8,
      "Projeto de Vida": 7,
      "OE - Língua Portuguesa": 6,
      "Educação Física": 10,
      "OE - Matemática": 7,
      Física: 6,
      "Aprofundamento de Geografia": 8,
      História: 7,
      "Língua Inglesa": 6,
      "Língua Portuguesa": 6,
      Matemática: 6,
      "Aprofundamento de Filosofia": 7,
      "Redação e Leitura": 5,
      "Aprofundamento de Sociologia": 8,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
  {
    nome: "Lara Cancian de Brito",
    notas: {
      Atualidades: 6,
      "Projeto de Vida": 6,
      "OE - Língua Portuguesa": 5,
      "Educação Física": 8,
      "OE - Matemática": 6,
      Física: 4,
      "Aprofundamento de Geografia": 7,
      História: 6,
      "Língua Inglesa": 6,
      "Língua Portuguesa": 5,
      Matemática: 5,
      "Aprofundamento de Filosofia": 7,
      "Redação e Leitura": 6,
      "Aprofundamento de Sociologia": 7,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Lara Silva Cordeiro",
    notas: {
      Atualidades: 4,
      "Projeto de Vida": 5,
      "OE - Língua Portuguesa": 4,
      "Educação Física": 8,
      "OE - Matemática": 5,
      Física: 4,
      "Aprofundamento de Geografia": 6,
      História: 4,
      "Língua Inglesa": 3,
      "Língua Portuguesa": 5,
      Matemática: 4,
      "Aprofundamento de Filosofia": 5,
      "Redação e Leitura": 6,
      "Aprofundamento de Sociologia": 4,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Livia Borges Ferreira",
    notas: {
      Atualidades: 7,
      "Projeto de Vida": 5,
      "OE - Língua Portuguesa": 9,
      "Educação Física": 6,
      "OE - Matemática": 6,
      Física: 5,
      "Aprofundamento de Geografia": 8,
      História: 8,
      "Língua Inglesa": 8,
      "Língua Portuguesa": 8,
      Matemática: 6,
      "Aprofundamento de Filosofia": 8,
      "Redação e Leitura": 6,
      "Aprofundamento de Sociologia": 8,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
  {
    nome: "Maria Julia Soares Brito",
    notas: {
      Atualidades: 8,
      "Projeto de Vida": 7,
      "OE - Língua Portuguesa": 7,
      "Educação Física": 8,
      "OE - Matemática": 6,
      Física: 6,
      "Aprofundamento de Geografia": 8,
      História: 8,
      "Língua Inglesa": 7,
      "Língua Portuguesa": 8,
      Matemática: 6,
      "Aprofundamento de Filosofia": 8,
      "Redação e Leitura": 7,
      "Aprofundamento de Sociologia": 8,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
  {
    nome: "Maria Rita Rodrigues de Paulo",
    notas: {
      Atualidades: 7,
      "Projeto de Vida": 6,
      "OE - Língua Portuguesa": 5,
      "Educação Física": 7,
      "OE - Matemática": 6,
      Física: 4,
      "Aprofundamento de Geografia": 7,
      História: 5,
      "Língua Inglesa": 5,
      "Língua Portuguesa": 4,
      Matemática: 4,
      "Aprofundamento de Filosofia": 7,
      "Redação e Leitura": 6,
      "Aprofundamento de Sociologia": 6,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Melissa Paschoalotto dos Santos",
    notas: {
      Atualidades: 4,
      "Projeto de Vida": 4,
      "OE - Língua Portuguesa": 5,
      "Educação Física": 8,
      "OE - Matemática": 5,
      Física: 4,
      "Aprofundamento de Geografia": 5,
      História: 4,
      "Língua Inglesa": 4,
      "Língua Portuguesa": 4,
      Matemática: 4,
      "Aprofundamento de Filosofia": 4,
      "Redação e Leitura": 6,
      "Aprofundamento de Sociologia": 5,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Pietra Cristina Santos Almeida",
    notas: {
      Atualidades: 7,
      "Projeto de Vida": 5,
      "OE - Língua Portuguesa": 6,
      "Educação Física": 7,
      "OE - Matemática": 5,
      Física: 4,
      "Aprofundamento de Geografia": 7,
      História: 5,
      "Língua Inglesa": 4,
      "Língua Portuguesa": 5,
      Matemática: 4,
      "Aprofundamento de Filosofia": 7,
      "Redação e Leitura": 5,
      "Aprofundamento de Sociologia": 7,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Raissa Remondini dos Santos",
    notas: {
      Atualidades: 8,
      "Projeto de Vida": 7,
      "OE - Língua Portuguesa": 7,
      "Educação Física": 7,
      "OE - Matemática": 6,
      Física: 6,
      "Aprofundamento de Geografia": 8,
      História: 7,
      "Língua Inglesa": 6,
      "Língua Portuguesa": 6,
      Matemática: 6,
      "Aprofundamento de Filosofia": 8,
      "Redação e Leitura": 7,
      "Aprofundamento de Sociologia": 8,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
  {
    nome: "Ruan Silva Fonseca",
    notas: {
      Atualidades: 9,
      "Projeto de Vida": 9,
      "OE - Língua Portuguesa": 8,
      "Educação Física": 9,
      "OE - Matemática": 8,
      Física: 9,
      "Aprofundamento de Geografia": 9,
      História: 9,
      "Língua Inglesa": 9,
      "Língua Portuguesa": 8,
      Matemática: 9,
      "Aprofundamento de Filosofia": 9,
      "Redação e Leitura": 8,
      "Aprofundamento de Sociologia": 9,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
  {
    nome: "Thamires Dias Leal",
    notas: {
      Atualidades: 7,
      "Projeto de Vida": 6,
      "OE - Língua Portuguesa": 7,
      "Educação Física": 8,
      "OE - Matemática": 6,
      Física: 6,
      "Aprofundamento de Geografia": 6,
      História: 7,
      "Língua Inglesa": 5,
      "Língua Portuguesa": 5,
      Matemática: 5,
      "Aprofundamento de Filosofia": 7,
      "Redação e Leitura": 4,
      "Aprofundamento de Sociologia": 5,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
]

// Dados do 6º Ano - Ensino Fundamental
const materias6Ano = [
  "Arte",
  "Ciências",
  "OE - Língua Portuguesa",
  "Educação Física",
  "Geografia",
  "História",
  "Língua Inglesa",
  "Língua Portuguesa",
  "Matemática",
  "Projeto de Vida",
  "Redação e Leitura",
  "OE - Matemática",
]

const alunos6Ano: Aluno[] = [
  {
    nome: "Alicia Maria Gea Silva",
    notas: {
      Arte: 9,
      Ciências: 10,
      "OE - Língua Portuguesa": 7,
      "Educação Física": 7,
      Geografia: 9,
      História: 8,
      "Língua Inglesa": 8,
      "Língua Portuguesa": 7,
      Matemática: 8,
      "Projeto de Vida": 9,
      "Redação e Leitura": 7,
      "OE - Matemática": 8,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
  {
    nome: "Ana Beatriz Souza da Silva",
    notas: {
      Arte: 7,
      Ciências: 3,
      "OE - Língua Portuguesa": 5,
      "Educação Física": 7,
      Geografia: 4,
      História: 5,
      "Língua Inglesa": 4,
      "Língua Portuguesa": 4,
      Matemática: 3,
      "Projeto de Vida": 7,
      "Redação e Leitura": 5,
      "OE - Matemática": 3,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Arthur César Dantas da Silva",
    notas: {
      Arte: 5,
      Ciências: 5,
      "OE - Língua Portuguesa": 5,
      "Educação Física": 8,
      Geografia: 3,
      História: 3,
      "Língua Inglesa": 2,
      "Língua Portuguesa": 1,
      Matemática: 4,
      "Projeto de Vida": 5,
      "Redação e Leitura": 3,
      "OE - Matemática": 4,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Davi Lucas Souza de Oliveira",
    notas: {
      Arte: 5,
      Ciências: 5,
      "OE - Língua Portuguesa": 1,
      "Educação Física": 5,
      Geografia: 3,
      História: 5,
      "Língua Inglesa": 4,
      "Língua Portuguesa": 3,
      Matemática: 4,
      "Projeto de Vida": 5,
      "Redação e Leitura": 2,
      "OE - Matemática": 4,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Davi Luiz Aquino de Araujo",
    notas: {
      Arte: 5,
      Ciências: 4,
      "OE - Língua Portuguesa": 3,
      "Educação Física": 7,
      Geografia: 3,
      História: 3,
      "Língua Inglesa": 2,
      "Língua Portuguesa": 2,
      Matemática: 3,
      "Projeto de Vida": 5,
      "Redação e Leitura": 3,
      "OE - Matemática": 3,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Eloa Vitoria dos Santos",
    notas: {
      Arte: 6,
      Ciências: 5,
      "OE - Língua Portuguesa": 5,
      "Educação Física": 7,
      Geografia: 5,
      História: 6,
      "Língua Inglesa": 4,
      "Língua Portuguesa": 3,
      Matemática: 4,
      "Projeto de Vida": 6,
      "Redação e Leitura": 5,
      "OE - Matemática": 6,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Emanuelly dos Santos Dias",
    notas: {
      Arte: 8,
      Ciências: 9,
      "OE - Língua Portuguesa": 8,
      "Educação Física": 8,
      Geografia: 9,
      História: 9,
      "Língua Inglesa": 8,
      "Língua Portuguesa": 7,
      Matemática: 9,
      "Projeto de Vida": 8,
      "Redação e Leitura": 8,
      "OE - Matemática": 9,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
  {
    nome: "Felix Gabriel de Souza Gil",
    notas: {
      Arte: 6,
      Ciências: 8,
      "OE - Língua Portuguesa": 5,
      "Educação Física": 8,
      Geografia: 5,
      História: 6,
      "Língua Inglesa": 6,
      "Língua Portuguesa": 5,
      Matemática: 6,
      "Projeto de Vida": 6,
      "Redação e Leitura": 5,
      "OE - Matemática": 7,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
  {
    nome: "Gabriel Henrique Dias da Silva",
    notas: {
      Arte: 5,
      Ciências: 4,
      "OE - Língua Portuguesa": 3,
      "Educação Física": 7,
      Geografia: 3,
      História: 4,
      "Língua Inglesa": 2,
      "Língua Portuguesa": 3,
      Matemática: 4,
      "Projeto de Vida": 4,
      "Redação e Leitura": 4,
      "OE - Matemática": 4,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Italo Gabriel Defacio da Silva",
    notas: {
      Arte: 5,
      Ciências: 6,
      "OE - Língua Portuguesa": 4,
      "Educação Física": 7,
      Geografia: 5,
      História: 5,
      "Língua Inglesa": 5,
      "Língua Portuguesa": 3,
      Matemática: 4,
      "Projeto de Vida": 5,
      "Redação e Leitura": 5,
      "OE - Matemática": 6,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Jean Carlos da Silva Cancian",
    notas: {
      Arte: 6,
      Ciências: 5,
      "OE - Língua Portuguesa": 4,
      "Educação Física": 5,
      Geografia: 5,
      História: 4,
      "Língua Inglesa": 5,
      "Língua Portuguesa": 4,
      Matemática: 3,
      "Projeto de Vida": 6,
      "Redação e Leitura": 5,
      "OE - Matemática": 5,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "João Vitor Barbosa Fiori",
    notas: {
      Arte: 6,
      Ciências: 8,
      "OE - Língua Portuguesa": 6,
      "Educação Física": 7,
      Geografia: 7,
      História: 7,
      "Língua Inglesa": 6,
      "Língua Portuguesa": 6,
      Matemática: 7,
      "Projeto de Vida": 6,
      "Redação e Leitura": 7,
      "OE - Matemática": 6,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
  {
    nome: "Julierme da Silva Ferreira",
    notas: {
      Arte: 5,
      Ciências: 5,
      "OE - Língua Portuguesa": 3,
      "Educação Física": 5,
      Geografia: 5,
      História: 4,
      "Língua Inglesa": 4,
      "Língua Portuguesa": 3,
      Matemática: 5,
      "Projeto de Vida": 5,
      "Redação e Leitura": 5,
      "OE - Matemática": 5,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Leonardo Aparecido dos Santos",
    notas: {
      Arte: 5,
      Ciências: 5,
      "OE - Língua Portuguesa": 3,
      "Educação Física": 7,
      Geografia: 4,
      História: 4,
      "Língua Inglesa": 2,
      "Língua Portuguesa": 3,
      Matemática: 3,
      "Projeto de Vida": 5,
      "Redação e Leitura": 4,
      "OE - Matemática": 4,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Maria Clara Cruz Toledo",
    notas: {
      Arte: 6,
      Ciências: 9,
      "OE - Língua Portuguesa": 5,
      "Educação Física": 7,
      Geografia: 7,
      História: 6,
      "Língua Inglesa": 6,
      "Língua Portuguesa": 5,
      Matemática: 5,
      "Projeto de Vida": 5,
      "Redação e Leitura": 7,
      "OE - Matemática": 6,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
  {
    nome: "Marina Santos Araujo",
    notas: {
      Arte: 7,
      Ciências: 8,
      "OE - Língua Portuguesa": 4,
      "Educação Física": 7,
      Geografia: 9,
      História: 8,
      "Língua Inglesa": 6,
      "Língua Portuguesa": 6,
      Matemática: 7,
      "Projeto de Vida": 7,
      "Redação e Leitura": 7,
      "OE - Matemática": 7,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Olivia Aparecida de Lima Cestari",
    notas: {
      Arte: 6,
      Ciências: 3,
      "OE - Língua Portuguesa": 5,
      "Educação Física": 7,
      Geografia: 4,
      História: 5,
      "Língua Inglesa": 6,
      "Língua Portuguesa": 4,
      Matemática: 4,
      "Projeto de Vida": 5,
      "Redação e Leitura": 5,
      "OE - Matemática": 5,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Rodrigo Bressa Reis",
    notas: {
      Arte: 8,
      Ciências: 8,
      "OE - Língua Portuguesa": 6,
      "Educação Física": 9,
      Geografia: 7,
      História: 7,
      "Língua Inglesa": 7,
      "Língua Portuguesa": 5,
      Matemática: 7,
      "Projeto de Vida": 7,
      "Redação e Leitura": 6,
      "OE - Matemática": 6,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
]

// Dados do 7º Ano - Ensino Fundamental
const materias7Ano = [
  "Arte",
  "Ciências",
  "Tecnologia",
  "Educação Física",
  "Geografia",
  "História",
  "Língua Inglesa",
  "Língua Portuguesa",
  "Matemática",
  "Projeto de Vida",
  "Redação e Leitura",
  "Educação Financeira",
]

const alunos7Ano: Aluno[] = [
  {
    nome: "Anallu Vivian Oliveira",
    notas: {
      Arte: 8,
      Ciências: 7,
      Tecnologia: 9,
      "Educação Física": 10,
      Geografia: 8,
      História: 8,
      "Língua Inglesa": 8,
      "Língua Portuguesa": 7,
      Matemática: 7,
      "Projeto de Vida": 8,
      "Redação e Leitura": 8,
      "Educação Financeira": 8,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
  {
    nome: "Diego Aquino dos Santos",
    notas: {
      Arte: 6,
      Ciências: 5,
      Tecnologia: 6,
      "Educação Física": 9,
      Geografia: 5,
      História: 5,
      "Língua Inglesa": 4,
      "Língua Portuguesa": 5,
      Matemática: 5,
      "Projeto de Vida": 6,
      "Redação e Leitura": 4,
      "Educação Financeira": 6,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Guilherme Aquino de Araujo",
    notas: {
      Arte: 6,
      Ciências: 6,
      Tecnologia: 5,
      "Educação Física": 10,
      Geografia: 4,
      História: 4,
      "Língua Inglesa": 3,
      "Língua Portuguesa": 3,
      Matemática: 3,
      "Projeto de Vida": 5,
      "Redação e Leitura": 3,
      "Educação Financeira": 5,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "João Gabriel Lopes da Silva",
    notas: {
      Arte: 6,
      Ciências: 4,
      Tecnologia: 6,
      "Educação Física": 9,
      Geografia: 4,
      História: 5,
      "Língua Inglesa": 6,
      "Língua Portuguesa": 4,
      Matemática: 3,
      "Projeto de Vida": 6,
      "Redação e Leitura": 4,
      "Educação Financeira": 6,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "João Miguel Almeida Vieira",
    notas: {
      Arte: 7,
      Ciências: 8,
      Tecnologia: 7,
      "Educação Física": 8,
      Geografia: 4,
      História: 4,
      "Língua Inglesa": 4,
      "Língua Portuguesa": 4,
      Matemática: 3,
      "Projeto de Vida": 6,
      "Redação e Leitura": 5,
      "Educação Financeira": 3,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Miguel Gonçalves de Lima",
    notas: {
      Arte: 7,
      Ciências: 9,
      Tecnologia: 8,
      "Educação Física": 8,
      Geografia: 8,
      História: 8,
      "Língua Inglesa": 7,
      "Língua Portuguesa": 8,
      Matemática: 8,
      "Projeto de Vida": 7,
      "Redação e Leitura": 9,
      "Educação Financeira": 8,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
  {
    nome: "Miguel Lima Neves",
    notas: {
      Arte: 7,
      Ciências: 6,
      Tecnologia: 8,
      "Educação Física": 8,
      Geografia: 5,
      História: 6,
      "Língua Inglesa": 4,
      "Língua Portuguesa": 5,
      Matemática: 5,
      "Projeto de Vida": 7,
      "Redação e Leitura": 6,
      "Educação Financeira": 7,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Neymar Henrique Ferreira da Silva",
    notas: {
      Arte: 6,
      Ciências: 5,
      Tecnologia: 9,
      "Educação Física": 9,
      Geografia: 6,
      História: 7,
      "Língua Inglesa": 5,
      "Língua Portuguesa": 6,
      Matemática: 5,
      "Projeto de Vida": 7,
      "Redação e Leitura": 6,
      "Educação Financeira": 7,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
  {
    nome: "Paula Fernanda da Silva",
    notas: {
      Arte: 7,
      Ciências: 6,
      Tecnologia: 7,
      "Educação Física": 8,
      Geografia: 4,
      História: 5,
      "Língua Inglesa": 5,
      "Língua Portuguesa": 3,
      Matemática: 3,
      "Projeto de Vida": 7,
      "Redação e Leitura": 5,
      "Educação Financeira": 6,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Pedro Augusto dos Santos Paulo",
    notas: {
      Arte: 8,
      Ciências: 7,
      Tecnologia: 7,
      "Educação Física": 7,
      Geografia: 4,
      História: 5,
      "Língua Inglesa": 8,
      "Língua Portuguesa": 6,
      Matemática: 6,
      "Projeto de Vida": 7,
      "Redação e Leitura": 8,
      "Educação Financeira": 7,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Pedro Ferreira dos Santos",
    notas: {
      Arte: 8,
      Ciências: 8,
      Tecnologia: 8,
      "Educação Física": 9,
      Geografia: 7,
      História: 8,
      "Língua Inglesa": 8,
      "Língua Portuguesa": 7,
      Matemática: 8,
      "Projeto de Vida": 8,
      "Redação e Leitura": 8,
      "Educação Financeira": 8,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
  {
    nome: "Pedro Henrique Aquino Fernandes",
    notas: {
      Arte: 9,
      Ciências: 9,
      Tecnologia: 9,
      "Educação Física": 10,
      Geografia: 9,
      História: 9,
      "Língua Inglesa": 8,
      "Língua Portuguesa": 9,
      Matemática: 9,
      "Projeto de Vida": 9,
      "Redação e Leitura": 8,
      "Educação Financeira": 9,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
  {
    nome: "Samuel José Cancian Altomar",
    notas: {
      Arte: 4,
      Ciências: 4,
      Tecnologia: 5,
      "Educação Física": 10,
      Geografia: 5,
      História: 4,
      "Língua Inglesa": 3,
      "Língua Portuguesa": 5,
      Matemática: 4,
      "Projeto de Vida": 5,
      "Redação e Leitura": 4,
      "Educação Financeira": 5,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Wellington Guilherme da Costa Borges",
    notas: {
      Arte: 4,
      Ciências: 4,
      Tecnologia: 4,
      "Educação Física": 7,
      Geografia: 3,
      História: 4,
      "Língua Inglesa": 2,
      "Língua Portuguesa": 2,
      Matemática: 2,
      "Projeto de Vida": 4,
      "Redação e Leitura": 3,
      "Educação Financeira": 5,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
]

// Dados do 8º Ano - Ensino Fundamental
const materias8Ano = [
  "Arte",
  "Ciências",
  "Tecnologia",
  "Educação Física",
  "Geografia",
  "História",
  "Língua Inglesa",
  "Língua Portuguesa",
  "Matemática",
  "Projeto de Vida",
  "Redação e Leitura",
  "Educação Financeira",
]

const alunos8Ano: Aluno[] = [
  {
    nome: "Daniel da Silva Morais",
    notas: {
      Arte: 8,
      Ciências: 9,
      Tecnologia: 9,
      "Educação Física": 9,
      Geografia: 8,
      História: 8,
      "Língua Inglesa": 6,
      "Língua Portuguesa": 7,
      Matemática: 6,
      "Projeto de Vida": 8,
      "Redação e Leitura": 8,
      "Educação Financeira": 7,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
  {
    nome: "Eduardo dos Santos Pereira",
    notas: {
      Arte: 5,
      Ciências: 5,
      Tecnologia: 5,
      "Educação Física": 5,
      Geografia: 5,
      História: 5,
      "Língua Inglesa": 5,
      "Língua Portuguesa": 5,
      Matemática: 5,
      "Projeto de Vida": 5,
      "Redação e Leitura": 5,
      "Educação Financeira": 5,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
  {
    nome: "Emanuelly Rodrigues Tagliari Magro",
    notas: {
      Arte: 7,
      Ciências: 7,
      Tecnologia: 8,
      "Educação Física": 8,
      Geografia: 8,
      História: 7,
      "Língua Inglesa": 7,
      "Língua Portuguesa": 7,
      Matemática: 4,
      "Projeto de Vida": 8,
      "Redação e Leitura": 8,
      "Educação Financeira": 6,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Erick Matheus da Silva Sima",
    notas: {
      Arte: 5,
      Ciências: 5,
      Tecnologia: 5,
      "Educação Física": 7,
      Geografia: 3,
      História: 5,
      "Língua Inglesa": 4,
      "Língua Portuguesa": 3,
      Matemática: 3,
      "Projeto de Vida": 5,
      "Redação e Leitura": 4,
      "Educação Financeira": 3,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Gildo Arthur Silva de Souza",
    notas: {
      Arte: 6,
      Ciências: 5,
      Tecnologia: 6,
      "Educação Física": 6,
      Geografia: 6,
      História: 5,
      "Língua Inglesa": 6,
      "Língua Portuguesa": 6,
      Matemática: 5,
      "Projeto de Vida": 6,
      "Redação e Leitura": 6,
      "Educação Financeira": 5,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
  {
    nome: "Iury Defendi Silva",
    notas: {
      Arte: 7,
      Ciências: 7,
      Tecnologia: 6,
      "Educação Física": 9,
      Geografia: 6,
      História: 7,
      "Língua Inglesa": 4,
      "Língua Portuguesa": 5,
      Matemática: 4,
      "Projeto de Vida": 7,
      "Redação e Leitura": 6,
      "Educação Financeira": 6,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Julio Cesar Rocha dos Santos",
    notas: {
      Arte: 7,
      Ciências: 7,
      Tecnologia: 7,
      "Educação Física": 7,
      Geografia: 5,
      História: 6,
      "Língua Inglesa": 4,
      "Língua Portuguesa": 5,
      Matemática: 4,
      "Projeto de Vida": 7,
      "Redação e Leitura": 7,
      "Educação Financeira": 4,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Lara Dantas da Silva",
    notas: {
      Arte: 6,
      Ciências: 7,
      Tecnologia: 6,
      "Educação Física": 8,
      Geografia: 4,
      História: 3,
      "Língua Inglesa": 4,
      "Língua Portuguesa": 4,
      Matemática: 3,
      "Projeto de Vida": 6,
      "Redação e Leitura": 6,
      "Educação Financeira": 4,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Livia Maria Gois Rego",
    notas: {
      Arte: 6,
      Ciências: 6,
      Tecnologia: 7,
      "Educação Física": 7,
      Geografia: 5,
      História: 5,
      "Língua Inglesa": 4,
      "Língua Portuguesa": 4,
      Matemática: 3,
      "Projeto de Vida": 7,
      "Redação e Leitura": 5,
      "Educação Financeira": 3,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Miguel Volpe da Silva Cacheffo",
    notas: {
      Arte: 9,
      Ciências: 9,
      Tecnologia: 9,
      "Educação Física": 8,
      Geografia: 8,
      História: 8,
      "Língua Inglesa": 6,
      "Língua Portuguesa": 8,
      Matemática: 7,
      "Projeto de Vida": 9,
      "Redação e Leitura": 8,
      "Educação Financeira": 8,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
  {
    nome: "Nicolas Muniz Santos Cancian",
    notas: {
      Arte: 9,
      Ciências: 9,
      Tecnologia: 9,
      "Educação Física": 9,
      Geografia: 10,
      História: 9,
      "Língua Inglesa": 7,
      "Língua Portuguesa": 9,
      Matemática: 8,
      "Projeto de Vida": 10,
      "Redação e Leitura": 9,
      "Educação Financeira": 8,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
  {
    nome: "Nicollas Massena Aquino",
    notas: {
      Arte: 9,
      Ciências: 9,
      Tecnologia: 9,
      "Educação Física": 8,
      Geografia: 9,
      História: 8,
      "Língua Inglesa": 6,
      "Língua Portuguesa": 7,
      Matemática: 8,
      "Projeto de Vida": 9,
      "Redação e Leitura": 8,
      "Educação Financeira": 8,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
  {
    nome: "Nicolly Neres dos Santos",
    notas: {
      Arte: 7,
      Ciências: 8,
      Tecnologia: 7,
      "Educação Física": 7,
      Geografia: 5,
      História: 7,
      "Língua Inglesa": 5,
      "Língua Portuguesa": 6,
      Matemática: 3,
      "Projeto de Vida": 7,
      "Redação e Leitura": 7,
      "Educação Financeira": 4,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Ralfh Gabriel Souza Santos",
    notas: {
      Arte: 8,
      Ciências: 9,
      Tecnologia: 8,
      "Educação Física": 7,
      Geografia: 8,
      História: 8,
      "Língua Inglesa": 8,
      "Língua Portuguesa": 8,
      Matemática: 8,
      "Projeto de Vida": 8,
      "Redação e Leitura": 8,
      "Educação Financeira": 8,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
  {
    nome: "Raphaely Bittencourt Araújo",
    notas: {
      Arte: 7,
      Ciências: 8,
      Tecnologia: 7,
      "Educação Física": 7,
      Geografia: 6,
      História: 6,
      "Língua Inglesa": 4,
      "Língua Portuguesa": 6,
      Matemática: 4,
      "Projeto de Vida": 7,
      "Redação e Leitura": 6,
      "Educação Financeira": 6,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Renan de Oliveira Rego",
    notas: {
      Arte: 6,
      Ciências: 5,
      Tecnologia: 6,
      "Educação Física": 6,
      Geografia: 5,
      História: 5,
      "Língua Inglesa": 4,
      "Língua Portuguesa": 4,
      Matemática: 3,
      "Projeto de Vida": 6,
      "Redação e Leitura": 5,
      "Educação Financeira": 4,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Yago Daniel Defacio da Silva",
    notas: {
      Arte: 6,
      Ciências: 7,
      Tecnologia: 7,
      "Educação Física": 7,
      Geografia: 5,
      História: 7,
      "Língua Inglesa": 5,
      "Língua Portuguesa": 6,
      Matemática: 5,
      "Projeto de Vida": 7,
      "Redação e Leitura": 7,
      "Educação Financeira": 5,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
  {
    nome: "Yandra Gabriella Conceição dos Santos",
    notas: {
      Arte: 6,
      Ciências: 7,
      Tecnologia: 7,
      "Educação Física": 7,
      Geografia: 4,
      História: 7,
      "Língua Inglesa": 3,
      "Língua Portuguesa": 5,
      Matemática: 4,
      "Projeto de Vida": 7,
      "Redação e Leitura": 3,
      "Educação Financeira": 5,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
]

// Dados do 9º Ano - Ensino Fundamental
const materias9Ano = [
  "Arte",
  "Ciências",
  "OE - Língua Portuguesa",
  "Educação Física",
  "Geografia",
  "História",
  "Língua Inglesa",
  "Língua Portuguesa",
  "Matemática",
  "Projeto de Vida",
  "Redação e Leitura",
  "OE - Matemática",
]

const alunos9Ano: Aluno[] = [
  {
    nome: "Ana Julia Araujo de Souza",
    notas: {
      Arte: 4,
      Ciências: 3,
      "OE - Língua Portuguesa": 4,
      "Educação Física": 5,
      Geografia: 3,
      História: 4,
      "Língua Inglesa": 3,
      "Língua Portuguesa": 3,
      Matemática: 2,
      "Projeto de Vida": 5,
      "Redação e Leitura": 4,
      "OE - Matemática": 2,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Andrey Pierre de Lima Cestari",
    notas: {
      Arte: 5,
      Ciências: 5,
      "OE - Língua Portuguesa": 4,
      "Educação Física": 8,
      Geografia: 6,
      História: 5,
      "Língua Inglesa": 4,
      "Língua Portuguesa": 4,
      Matemática: 3,
      "Projeto de Vida": 5,
      "Redação e Leitura": 5,
      "OE - Matemática": 4,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Bettina Paschoalotto dos Santos",
    notas: {
      Arte: 6,
      Ciências: 4,
      "OE - Língua Portuguesa": 6,
      "Educação Física": 7,
      Geografia: 4,
      História: 4,
      "Língua Inglesa": 5,
      "Língua Portuguesa": 6,
      Matemática: 4,
      "Projeto de Vida": 6,
      "Redação e Leitura": 6,
      "OE - Matemática": 4,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Davi Fernandes Consoli",
    notas: {
      Arte: 8,
      Ciências: 7,
      "OE - Língua Portuguesa": 7,
      "Educação Física": 10,
      Geografia: 9,
      História: 8,
      "Língua Inglesa": 7,
      "Língua Portuguesa": 8,
      Matemática: 5,
      "Projeto de Vida": 8,
      "Redação e Leitura": 7,
      "OE - Matemática": 7,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
  {
    nome: "Elias Gabriel Batista de Souza",
    notas: {
      Arte: 4,
      Ciências: 5,
      "OE - Língua Portuguesa": 4,
      "Educação Física": 9,
      Geografia: 6,
      História: 5,
      "Língua Inglesa": 4,
      "Língua Portuguesa": 6,
      Matemática: 4,
      "Projeto de Vida": 5,
      "Redação e Leitura": 5,
      "OE - Matemática": 5,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Eloá Alves de Oliveira",
    notas: {
      Arte: 8,
      Ciências: 7,
      "OE - Língua Portuguesa": 8,
      "Educação Física": 8,
      Geografia: 8,
      História: 8,
      "Língua Inglesa": 7,
      "Língua Portuguesa": 9,
      Matemática: 5,
      "Projeto de Vida": 8,
      "Redação e Leitura": 9,
      "OE - Matemática": 5,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
  {
    nome: "Enzo Gabriel Gois Furini",
    notas: {
      Arte: 7,
      Ciências: 4,
      "OE - Língua Portuguesa": 5,
      "Educação Física": 8,
      Geografia: 5,
      História: 4,
      "Língua Inglesa": 4,
      "Língua Portuguesa": 5,
      Matemática: 3,
      "Projeto de Vida": 7,
      "Redação e Leitura": 6,
      "OE - Matemática": 4,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Felipe Henrique Aquino Domingos",
    notas: {
      Arte: 7,
      Ciências: 5,
      "OE - Língua Portuguesa": 6,
      "Educação Física": 10,
      Geografia: 6,
      História: 5,
      "Língua Inglesa": 5,
      "Língua Portuguesa": 6,
      Matemática: 4,
      "Projeto de Vida": 8,
      "Redação e Leitura": 7,
      "OE - Matemática": 5,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Gabriel Antônio Cestari Pacheco",
    notas: {
      Arte: 5,
      Ciências: 3,
      "OE - Língua Portuguesa": 4,
      "Educação Física": 7,
      Geografia: 3,
      História: 4,
      "Língua Inglesa": 3,
      "Língua Portuguesa": 3,
      Matemática: 3,
      "Projeto de Vida": 5,
      "Redação e Leitura": 5,
      "OE - Matemática": 2,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Gabryel Batista dos Santos",
    notas: {
      Arte: 6,
      Ciências: 6,
      "OE - Língua Portuguesa": 5,
      "Educação Física": 7,
      Geografia: 5,
      História: 5,
      "Língua Inglesa": 5,
      "Língua Portuguesa": 6,
      Matemática: 3,
      "Projeto de Vida": 6,
      "Redação e Leitura": 6,
      "OE - Matemática": 4,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Isabella Souza Ferreira",
    notas: {
      Arte: 8,
      Ciências: 6,
      "OE - Língua Portuguesa": 6,
      "Educação Física": 7,
      Geografia: 6,
      História: 5,
      "Língua Inglesa": 6,
      "Língua Portuguesa": 7,
      Matemática: 4,
      "Projeto de Vida": 8,
      "Redação e Leitura": 8,
      "OE - Matemática": 6,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Jose Henrique Rabelo da Silva",
    notas: {
      Arte: 8,
      Ciências: 6,
      "OE - Língua Portuguesa": 7,
      "Educação Física": 10,
      Geografia: 8,
      História: 6,
      "Língua Inglesa": 6,
      "Língua Portuguesa": 7,
      Matemática: 5,
      "Projeto de Vida": 8,
      "Redação e Leitura": 7,
      "OE - Matemática": 6,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
  {
    nome: "Kauã Henrique Benite dos Santos",
    notas: {
      Arte: 7,
      Ciências: 4,
      "OE - Língua Portuguesa": 5,
      "Educação Física": 9,
      Geografia: 6,
      História: 7,
      "Língua Inglesa": 5,
      "Língua Portuguesa": 7,
      Matemática: 5,
      "Projeto de Vida": 7,
      "Redação e Leitura": 7,
      "OE - Matemática": 6,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Leonardo Silva Domingos Rosa",
    notas: {
      Arte: 5,
      Ciências: 5,
      "OE - Língua Portuguesa": 6,
      "Educação Física": 5,
      Geografia: 6,
      História: 5,
      "Língua Inglesa": 7,
      "Língua Portuguesa": 7,
      Matemática: 3,
      "Projeto de Vida": 6,
      "Redação e Leitura": 7,
      "OE - Matemática": 4,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Maria Fernanda dos Santos Cellis",
    notas: {
      Arte: 5,
      Ciências: 3,
      "OE - Língua Portuguesa": 3,
      "Educação Física": 5,
      Geografia: 5,
      História: 5,
      "Língua Inglesa": 4,
      "Língua Portuguesa": 4,
      Matemática: 3,
      "Projeto de Vida": 5,
      "Redação e Leitura": 6,
      "OE - Matemática": 4,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Miguel Junior Beijamim de Almeida",
    notas: {
      Arte: 5,
      Ciências: 4,
      "OE - Língua Portuguesa": 2,
      "Educação Física": 8,
      Geografia: 4,
      História: 4,
      "Língua Inglesa": 3,
      "Língua Portuguesa": 2,
      Matemática: 2,
      "Projeto de Vida": 8,
      "Redação e Leitura": 5,
      "OE - Matemática": 3,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Mirella Sales dos Santos",
    notas: {
      Arte: 8,
      Ciências: 7,
      "OE - Língua Portuguesa": 6,
      "Educação Física": 8,
      Geografia: 7,
      História: 7,
      "Língua Inglesa": 5,
      "Língua Portuguesa": 8,
      Matemática: 5,
      "Projeto de Vida": 8,
      "Redação e Leitura": 8,
      "OE - Matemática": 7,
    },
    media: 0,
    classificacao: "",
    atencao: false,
  },
  {
    nome: "Valentina Matheus da Silva",
    notas: {
      Arte: 6,
      Ciências: 4,
      "OE - Língua Portuguesa": 3,
      "Educação Física": 7,
      Geografia: 4,
      História: 4,
      "Língua Inglesa": 5,
      "Língua Portuguesa": 5,
      Matemática: 2,
      "Projeto de Vida": 6,
      "Redação e Leitura": 6,
      "OE - Matemática": 5,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
  {
    nome: "Mirely da Silva Ferreira",
    notas: {
      Arte: 4,
      Ciências: 4,
      "OE - Língua Portuguesa": 4,
      "Educação Física": 5,
      Geografia: 5,
      História: 5,
      "Língua Inglesa": 3,
      "Língua Portuguesa": 4,
      Matemática: 4,
      "Projeto de Vida": 4,
      "Redação e Leitura": 5,
      "OE - Matemática": 5,
    },
    media: 0,
    classificacao: "",
    atencao: true,
  },
]

// Função para processar alunos (calcular média e classificação)
function processarAlunos(alunos: Aluno[]): Aluno[] {
  return alunos.map((aluno) => {
    const media = calcularMedia(aluno.notas)
    return {
      ...aluno,
      media,
      classificacao: classificarNota(media),
    }
  })
}

// Montar todas as turmas
export const escolaData: EscolaData = {
  nome: "EE Carlos Bernardes Staut",
  endereco: "Rua Antônio Bueno da Costa, 65",
  cidade: "Ribeirão dos Índios - SP",
  bimestre: "1º Bimestre",
  dataConselho: "08/05/2026",
  turmas: [
    {
      id: "6-ano",
      nome: "6º Ano",
      nivel: "Ensino Fundamental",
      bimestre: "1º Bimestre",
      totalAlunos: 18,
      materias: materias6Ano,
      alunos: processarAlunos(alunos6Ano),
    },
    {
      id: "7-ano",
      nome: "7º Ano",
      nivel: "Ensino Fundamental",
      bimestre: "1º Bimestre",
      totalAlunos: 14,
      materias: materias7Ano,
      alunos: processarAlunos(alunos7Ano),
    },
    {
      id: "8-ano",
      nome: "8º Ano",
      nivel: "Ensino Fundamental",
      bimestre: "1º Bimestre",
      totalAlunos: 18,
      materias: materias8Ano,
      alunos: processarAlunos(alunos8Ano),
    },
    {
      id: "9-ano",
      nome: "9º Ano",
      nivel: "Ensino Fundamental",
      bimestre: "1º Bimestre",
      totalAlunos: 19,
      materias: materias9Ano,
      alunos: processarAlunos(alunos9Ano),
    },
    {
      id: "1-serie",
      nome: "1ª Série",
      nivel: "Ensino Médio",
      bimestre: "1º Bimestre",
      totalAlunos: 16,
      materias: materias1Serie,
      alunos: processarAlunos(alunos1Serie),
    },
    {
      id: "2-serie",
      nome: "2ª Série",
      nivel: "Ensino Médio",
      bimestre: "1º Bimestre",
      totalAlunos: 10,
      materias: materias2Serie,
      alunos: processarAlunos(alunos2Serie),
    },
    {
      id: "3-serie",
      nome: "3ª Série",
      nivel: "Ensino Médio",
      bimestre: "1º Bimestre",
      totalAlunos: 25,
      materias: materias3Serie,
      alunos: processarAlunos(alunos3Serie),
    },
  ],
}

// Funções de estatísticas
export function getEstatisticasGerais() {
  const todasTurmas = escolaData.turmas
  const todosAlunos = todasTurmas.flatMap((t) => t.alunos)
  const totalAlunos = todosAlunos.length
  const totalTurmas = todasTurmas.length
  const alunosCriticos = todosAlunos.filter((a) => a.media < 5).length
  const mediaGeral = Number((todosAlunos.reduce((acc, a) => acc + a.media, 0) / totalAlunos).toFixed(1))

  // Melhor e pior turma
  const turmasComMedia = todasTurmas.map((t) => ({
    ...t,
    mediaGeral: Number((t.alunos.reduce((acc, a) => acc + a.media, 0) / t.alunos.length).toFixed(1)),
  }))

  const melhorTurma = turmasComMedia.reduce((a, b) => (a.mediaGeral > b.mediaGeral ? a : b))
  const piorTurma = turmasComMedia.reduce((a, b) => (a.mediaGeral < b.mediaGeral ? a : b))

  return {
    totalAlunos,
    totalTurmas,
    alunosCriticos,
    mediaGeral,
    melhorTurma: { nome: melhorTurma.nome, media: melhorTurma.mediaGeral },
    piorTurma: { nome: piorTurma.nome, media: piorTurma.mediaGeral },
  }
}

export function getDistribuicaoPedagogica(alunos: Aluno[]) {
  const distribuicao = {
    "Abaixo do Básico": 0,
    Básico: 0,
    Adequado: 0,
    Avançado: 0,
  }

  alunos.forEach((aluno) => {
    if (aluno.classificacao in distribuicao) {
      distribuicao[aluno.classificacao as keyof typeof distribuicao]++
    }
  })

  return Object.entries(distribuicao).map(([name, value]) => ({
    name,
    value,
    fill:
      name === "Abaixo do Básico"
        ? "var(--chart-1)"
        : name === "Básico"
          ? "var(--chart-2)"
          : name === "Adequado"
            ? "var(--chart-3)"
            : "var(--chart-4)",
  }))
}

export function getMediaPorMateria(turma: Turma) {
  return turma.materias.map((materia) => {
    const notas = turma.alunos
      .map((a) => a.notas[materia])
      .filter((n): n is number => typeof n === "number")
    const media = notas.length > 0 ? Number((notas.reduce((a, b) => a + b, 0) / notas.length).toFixed(1)) : 0
    return {
      materia: materia.length > 15 ? materia.substring(0, 15) + "..." : materia,
      materiaCompleta: materia,
      media,
      classificacao: classificarNota(media),
    }
  })
}

export function getAlunosEmAtencao() {
  return escolaData.turmas.flatMap((turma) =>
    turma.alunos
      .filter((a) => a.atencao || a.media < 5)
      .map((aluno) => {
        const materiasAbaixo = Object.entries(aluno.notas)
          .filter(([, nota]) => typeof nota === "number" && nota < 5)
          .map(([materia]) => materia)
        return {
          ...aluno,
          turma: turma.nome,
          turmaId: turma.id,
          materiasAbaixo,
        }
      })
  )
}
